<h1 align="center">Física Computacional.</h1>
<h1 align="center">Semestre 2015-1</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Rodrigo Vega Vilchis
### Joel Gómez Uribe
---

<h1 align="center" font-weight="bold">Tarea-Práctica 7.</h1> 
<h2 align="center">Métodos de solución numérica para ecuaciones lineales y no lineales</h2> 
<hr>

In [144]:
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
from scipy import constants

plt.rcParams.update({
    "text.usetex": True,
})

<h2>1. Descomposición LU</h2>

<h3>(a) Escribe un programa que calcule la <strong>descomposición LU</strong> de una matriz</h3>

In [194]:
A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
v = np.array([-4, 3, 9, 7])
dim, _ = A.shape # Dimensión de la matriz

U_temp = [] # [L0, L1, L2, L3]
AA = A.copy() # Copia para no modificar la matriz original
U = np.eye(dim)
L = np.eye(dim)

for n in range(dim):
    L_n = np.eye(dim)
    pivote = AA[n, n]
    AA[n,:] /= pivote

    for ele in range(n + 1, dim):
        mult = AA[ele, n]
        L_n[ele, n] = -mult / pivote
        AA[ele, :] -= mult * A[n, :]
        
    U_temp.append(L_n) 
    U = L_n @ U #L0L1L2L3
    
# Matriz L
for L_n in U_temp:
    L = L @ np.linalg.inv(L_n)
    
print(f"La matriz original es: \n{A}")
# Recuperamos la matriz original LU = A
print(f"LU = A: \n{L @ U @ A}")

La matriz original es: 
[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
LU = A: 
[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


<h3>(b) Prueba tu programa</h3>

Calcula la descomposición LU de la matriz:

$$
    \begin{equation}
        \begin{pmatrix}
            2 & 1 & 4 & 2\\
            3 & 4 & -1 & -1\\
            1 & -4 & 1 & 5\\
            2 & -2 & 1 & 3
        \end{pmatrix}
        \begin{pmatrix}
        w \\ x \\ y \\ z
        \end{pmatrix}
        =
        \begin{pmatrix}
            -4\\ 3\\ 9\\ 7
        \end{pmatrix}
        \label{eq:sist1}
    \end{equation}
$$

<h3>(c) Multiplica las matrices $\mathbb{L}$ y $\mathbb{U}$</h3>

<h3>(d) Convierte tu programa en función</h3>

<h3>(e) Usa numpy para resolver</h3>

In [195]:
A = np.array([[2, 1, 4, 1], [3, 4, -1, -1], [1, -4, 1, 5], [2, -2, 1, 3]], float)
v = np.array([-4, 3, 9, 7])

P, L, U = sp.linalg.lu(A)
print(P @ L @ U)

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]


<h2>2. Pozo cuántico asimétrico</h2>

<h3>(a) Demuestra que la ec. de Schrödinger se puede escribir en forma matricial</h3>

<h3>(b) Escribe un programa para evular tu expresión para $H_{mn}$</h3>

<h3>(c) Calcula los valores propios de esta matriz</h3>

<h3>(d) Usa una matriz $100\times 100$</h3>

<h3>(e) Calcula la función de onda $\psi(x)$ para el estado fundamental y los dos primeros estados excitados</h3>

<h2>3. Método de relajación</h2>

Considera la ecuación $x = 1 - \mathrm{e}^{-cx}$, donde $c$ es un parámetro conocido y $x$ desconocido.

<h3>(a) Resuelve la ecuación por método de relajación</h3>

<h3>(b) Soluciones para valores de $c$ específicos</h3>

<h2>4. Glucólisis</h2>

<h3>(a) Demuestre analíticamente las soluciones</h3>
La solución de estas ecuaciones es:

$$
    \begin{equation*}
        x = b,\qquad y= \dfrac{b}{a + b^{2}}
    \end{equation*}
$$

<h3>(b) Resuelve por método de relajación</h3>

<h3>(c) Encuentra una forma diferente de reorganizar</h3>

<h2>5. Constante de desplazamiento de Wien</h2>

<h3>(a) Demuestra que $\lambda$ obedece al desplazamiento de Wienley</h3>

<h3>(b) Resolver ecuación con precisión $\epsilon = 10^{-6}$</h3>

<h3>(c) Estima la temperatura de la superficie del Sol</h3>

<h2>6. El punto de Lagrange</h2>

<h3>(a) Demuestra que la distancia $r$ satisface una ecuación</h3>

<h3>(b) Resuelve usando el método de Newton</h3>